Mimic.copy(ElixIRCd.Command)
Mimic.copy(ElixIRCd.Command.Cap)
Mimic.copy(ElixIRCd.Command.Join)
Mimic.copy(ElixIRCd.Command.Mode)
Mimic.copy(ElixIRCd.Command.Nick)
Mimic.copy(ElixIRCd.Command.Part)
Mimic.copy(ElixIRCd.Command.Ping)
Mimic.copy(ElixIRCd.Command.Privmsg)
Mimic.copy(ElixIRCd.Command.Quit)
Mimic.copy(ElixIRCd.Command.User)
Mimic.copy(ElixIRCd.Command.Userhost)
Mimic.copy(ElixIRCd.Command.Whois)
Mimic.copy(ElixIRCd.Server)

ExUnit.start()
