name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          target: runtime
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            faelgabriel/elixircd:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'pr-' }}${{ github.event.number }}
            faelgabriel/elixircd:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_VERSION=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}

      - name: Update Docker Hub description
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: faelgabriel/elixircd
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
