name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_dev:
    name: Docker Development Image Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          target: development
          push: false
          tags: elixircd:development
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_prod:
    name: Docker Production Image Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          target: production
          push: false
          tags: elixircd:production
          cache-from: type=gha
          cache-to: type=gha,mode=max
