name: Release

on:
  push:
    tags:
      - "*.*.*"

env:
  ELIXIR_VERSION: "1.16.1"
  OTP_VERSION: "26.2.2"
  MIX_ENV: "prod"

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    name: Build on Linux (x86_64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Install dependencies
        run: mix deps.get --only prod

      - name: Build release
        run: mix release

      - name: Package release
        run: tar -czvf elixircd-${{ github.ref_name }}-linux-x86_64.tar.gz -C _build/prod/rel/elixircd .

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: elixircd-${{ github.ref_name }}-linux-x86_64.tar.gz

  build-windows-x86_64:
    runs-on: windows-latest
    name: Build on Windows (x86_64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Install dependencies
        run: mix deps.get --only prod

      - name: Build release
        run: mix release

      - name: Package release
        run: powershell Compress-Archive -Path _build\prod\rel\elixircd\* -DestinationPath elixircd-${{ github.ref_name }}-windows-x86_64.zip

      - name: Upload release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: elixircd-${{ github.ref_name }}-windows-x86_64.zip
